name: Synthesis

on:
  pull_request:

jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
      - name: Install nextpnr/Trellis
        run: |
          sudo apt-get update
          sudo apt-get install -y nextpnr-ecp5 trellis
      - name: sbt synth
        run: sbt synth
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: utilization
          path: output/utilization.rpt
